import "@/app/globals.css";
import { AuthProvider } from "@/context/AuthContext";
import MyApp from '@/components/_app';
import { I18nextProvider } from "@/app/i18n/client";
import Footers from "@/components/Footer";
import Component from "@/components/Navbar";
import Options from "@/components/Options";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children, params }) {
  const { lng } = await params;
  return (
    <I18nextProvider lng={lng}>
      <AuthProvider>
        <MyApp>
          <Component/>
          {children}
          <Options/>
          <Footers/>
        </MyApp>
      </AuthProvider>
    </I18nextProvider>
  )
}
